env: development
address:
  internal: 'http://127.0.0.1:8081'
  external: 'http://127.0.0.1:8081'
dirs:
  main: 'C:/NodeJS/OpenCharity'
  public: 'C:/NodeJS/OpenCharity/public/'
  storage: 'C:/NodeJS/OpenCharity/storage/'