env: staging
address:
  internal: 'http://0.0.0.0:8080'
  external: 'https://meta.staging.bankex.team'
mongoURI: 'mongodb://meta:testpass@meta_mongodb:27017/meta'
cabinet: 'https://donatorscab.staging.bankex.team'
opencharity: 'https://opencharity.staging.bankex.team'
dapp:
  ws: 'wss://wsprovider.staging.bankex.team:8636'
  token: '0x6a183381d14371b4a228cca37802c09bd166ba9e'
dirs:
  main: '/oc_meta/'
  public: '/oc_meta/public/'
  storage: '/oc_meta/storage/'
cors:
  - 'https://donatorscab.staging.bankex.team'
  - 'https://opencharity.staging.bankex.team'
  - 'https://meta.staging.bankex.team'
  - 'http://127.0.0.1:8080'
  - 'http://127.0.0.1:8081'
  - 'http://127.0.0.1:8082'
  - 'http://127.0.0.1:3000'